repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.11.1
    hooks:
    -   id: pylint

-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v4.0.1
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-black
    rev: v20.8b1
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-pytest
    rev: v2.11.2
    hooks:
    -   id: pytest

# Vous pouvez ajouter d'autres hooks au besoin
